fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.23.0"
    archive:
      repo: "git://github.com/voxpupuli/puppet-archive.git"
      ref: "v1.3.0"
    concat:
      repo: "git://github.com/puppetlabs/puppet-concat.git"
      ref: "2.2.1"
  symlinks:
    consul_template: "#{source_dir}"
    consul_template_spec: "#{source_dir}/spec/fixtures/consul_template_spec"
